name: CI Default

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tuist
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Check Tuist
        run: tuist version

      - name: Check whitespace
        run: git diff --check

      - name: Test
        run: make test
